fix(actions): add prerelease-type input to update-pom-to-next-prerelease action
Alfresco/alfresco-build-tools pull request #177
Opened 2022-11-10 17:39 UTC by igdianov

- [x] add missing `prerelease-type` input optional parameter to be able to specify prerelease-type, i.e. `rc`, `beta` when using `update-pom-to-next-prerelease` action from `alfresco-process-releases` workflows

2022-11-14 09:10 UTC, atchertchian approved these changes

2022-11-14 09:27 UTC, atchertchian requested changes
Please reference AAE-11332 in the commit message: we should have that PR listed alongside others in jira

2022-11-14 18:32 UTC, igdianov commented
@atchertchian I have updated the commit and PR titles to use Jira ticket AAE-11332

2022-11-14 18:33 UTC, atchertchian approved these changes

2022-11-15 13:59 UTC, erdemedeiros approved these changes
LGTM!

2022-11-15 14:39 UTC, merged