ACS-3844 Add setup-build-tools action for standard setup of Java/Maven
Alfresco/alfresco-build-tools pull request #189
Opened 2022-11-25 14:31 UTC by dsibilio

Added a reusable generic action for standardized setup of Java and Maven for CI purposes.

2022-11-25 15:09 UTC, damianujma submitted a review, later dismissed
LGTM!

2022-11-25 15:53 UTC, gionn requested changes

2022-11-25 15:53 UTC, gionn commented on .github/actions/setup-java-build/action.yml
> +      uses: actions/cache@v2
```suggestion
      uses: actions/cache@v3
```

will also fix the deprecation notices you should have seen

2022-11-25 16:24 UTC, gionn approved these changes

2022-11-28 08:40 UTC, damianujma approved these changes

2022-12-13 13:18 UTC, merged