get pr number action
Alfresco/alfresco-build-tools pull request #248
Opened 2023-03-23 10:38 UTC by maurizio-cacace

2023-03-23 13:44 UTC, gionn requested changes
remember to also add it into the main readme

2023-03-24 10:28 UTC, gionn requested changes

2023-03-24 10:28 UTC, gionn commented on .github/workflows/devel-mau.yml
remove this file you used for testing

2023-03-27 08:56 UTC, maurizio-cacace commented
PR deprecated by https://github.com/Alfresco/alfresco-build-tools/pull/249

2023-03-27 08:56 UTC, closed without merging