OPSEXP-2084 Remove any travis configuration from alfresco-build-tools
Alfresco/alfresco-build-tools pull request #269
Opened 2023-06-06 11:18 UTC by slohe1

OPSEXP-2084

2023-06-06 12:34 UTC, gionn requested changes

2023-06-06 12:34 UTC, gionn commented on .github/actions/travis-env-load/action.yml
> -name: "travis-env-load"
this action it's actually still useful, I would keep it but switch to a better name which doesn't mention travis?

`env-load-from-yaml`

2023-06-07 16:54 UTC, alxgomz submitted a review, later dismissed
wait for @gionn 's review

2023-06-08 07:28 UTC, gionn requested changes

2023-06-08 07:28 UTC, gionn commented on docs/README.md
> -    - [travis-env-load](#travis-env-load)
if you install markdown all in one vscode it automatically update this TOC, otherwise make sure it's linked as before

2023-06-08 09:23 UTC, gionn approved these changes

2023-06-08 10:54 UTC, merged