OPSEXP-2106 add new action pipenv
Alfresco/alfresco-build-tools pull request #277
Opened 2023-06-21 07:48 UTC by slohe1

2023-06-21 10:48 UTC, gionn requested changes

2023-06-21 10:48 UTC, gionn commented on .github/actions/pipenv/requirements.txt
> +pipenv==2023.6.12
there is also a dependabot configuration that needs to be moved in order to keep this updated

2023-06-21 10:48 UTC, gionn commented on .github/actions/pipenv/action.yml
> +      run: pipenv install --deploy --dev --python $(cat .python-version)
remember to always add a readme entry for each new action

document also that the .python-version file in the repo root is a requirement (for now)

2023-06-21 13:29 UTC, alxgomz reviewed
Shouldn't this action setup/python as well?

2023-06-21 14:20 UTC, gionn commented
> Shouldn't this action setup/python as well?

I prefer to avoid it and push on composability in the workflow, otherwise we tend to have too much restrictive actions and little added utility overall

2023-06-21 14:24 UTC, gionn requested changes

2023-06-22 12:31 UTC, gionn commented on docs/README.md
> +This workflow sets up a Python environment with version 3.9 using the actions/setup-python@v4 action and utilizes the pipenv action to manage Python dependencies based on the specified Python version
```suggestion
This workflow sets up a Python environment using the standard setup-python action and utilizes the pipenv action to manage Python dependencies declared in the Pipfile and based on the specified Python version
```

2023-06-22 13:57 UTC, gionn approved these changes

2023-06-22 14:16 UTC, merged