ACS-6300 Add a static-name flag for reportportal-prepare action
Alfresco/alfresco-build-tools pull request #386
Opened 2023-11-23 12:33 UTC by wojtekswieton

2023-11-23 12:47 UTC, MichalFidor approved these changes
lgtm

2023-11-23 12:48 UTC, dsibilio requested changes

2023-11-23 12:48 UTC, dsibilio commented on .github/actions/reportportal-prepare/action.yml
> +  rp-static-name:
```suggestion
  rp-static-launch-name:
```

A more descriptive name might help.

2023-11-23 12:48 UTC, dsibilio commented on .github/actions/reportportal-prepare/action.yml
> +      If set, it uses RP_LAUNCH_PREFIX as RP_LAUNCH_KEY.
```suggestion
    description: If set, the rp-launch-prefix will be used as the full launch name in Report Portal
```

2023-11-23 12:48 UTC, dsibilio commented on .github/actions/reportportal-prepare/action.yml
> +      If set, it uses RP_LAUNCH_PREFIX as RP_LAUNCH_KEY.
^ would make it easier to understand from a consumer-perspective

2023-11-23 12:48 UTC, dsibilio commented on .github/actions/reportportal-prepare/action.yml
> +        STATIC: ${{ inputs.rp-static-name }}
```suggestion
        STATIC_LAUNCH_NAME: ${{ inputs.rp-static-launch-name }}
```

2023-11-23 12:48 UTC, dsibilio commented on .github/actions/reportportal-prepare/get-rp-input.sh
> +  if [[ "$AUTO" == "true" && "$STATIC" == "false" ]]; then
```suggestion
  if [[ "$AUTO" == "true" && "$STATIC_LAUNCH_NAME" == "false" ]]; then
```

2023-11-23 12:57 UTC, dsibilio requested changes

2023-11-23 12:57 UTC, dsibilio commented on docs/README.md
> +By using the `rp-static-launch-name` flag, you can determine whether 'LAUNCH_NAME' should be static or unique for each execution. By default, it is set to `false`.
```suggestion
By using the `rp-static-launch-name` flag, you can determine whether the launch name in Report Portal should be static or unique for each execution. By default, it is set to `false`.
```

Make it clearer for the consumer, they shouldn't have to go through the bash script implementation to understand what a new flag does.

2023-11-23 13:06 UTC, dsibilio commented
Few test failures [here](https://github.com/Alfresco/alfresco-build-tools/actions/runs/6970049366/job/18967180738?pr=386#step:4:17) need to be looked at and addressed.

2023-11-23 13:22 UTC, dsibilio requested changes
https://github.com/Alfresco/alfresco-build-tools/pull/386#issuecomment-1824409670

2023-11-23 13:24 UTC, atchertchian commented on .github/actions/reportportal-prepare/get-rp-input.sh
> +  if [[ "$AUTO" == "true" && "$STATIC_LAUNCH_NAME" == "false" ]]; then
```suggestion
  if [[ "$AUTO" == "true" && "$USE_STATIC_LAUNCH_NAME" == "false" ]]; then
```

2023-11-23 16:10 UTC, dsibilio approved these changes
LGTM ✔️ 

_Please, next time don't delete the PR template but fill it appropriately. It's there for a reason 👍_

@atchertchian thank you very much for your help!

2023-11-23 16:15 UTC, gionn approved these changes
> Please, next time don't delete the PR template but fill it appropriately. It's there for a reason 👍

![](https://media.tenor.com/7c9SRt5s1fQAAAAC/this-displeases-me-displease.gif)

2023-11-27 10:04 UTC, gionn approved these changes

2023-11-27 10:04 UTC, merged