Do not checkout in pre-commit action
Alfresco/alfresco-build-tools pull request #47
Opened 2022-04-29 10:16 UTC by gionn

Initially it looked handy given that pre-commit is often the first step of a job, but unfortunately that will overwrite any previous checkout invocation for which the user may have provided additional parameters.

Required in https://github.com/Alfresco/security-testing-travis/pull/15

2022-04-29 13:57 UTC, Mieszko96 approved these changes

2022-04-29 23:02 UTC, mteodori requested changes
this pre-commit action doesn't look particularly valuable, I would delete it completely

2022-05-03 10:26 UTC, gionn commented
> this pre-commit action doesn't look particularly valuable, I would delete it completely

it's just a starter for now, in the future I think we can use it as an hook to handle pre-commit for multiple repos in a single place

I am going to close this since if some repository requires a particular checkout configuration, is sufficient to move the checkout AFTER executing pre-commit to avoid overwriting it.

2022-05-03 10:26 UTC, closed without merging

2022-05-07 17:01 UTC, mteodori commented
Let's delete it, it's a few line of code of reuse that bring more side effect than value thanks