docs: add generate-dependabot-glob-action in readme
Alfresco/alfresco-build-tools pull request #515
Opened 2024-03-01 11:18 UTC by giacomoaluigi

- [README](https://github.com/Alfresco/alfresco-build-tools/blob/master/docs/README.md) updated after adding/changing behaviour of an action

### Description
Add generate-dependabot-glob-action documentation to _GitHub Actions provided by community_ section.

2024-03-01 12:02 UTC, gionn commented on docs/README.md
> +```
```suggestion
For example, the following template:

```
  - package-ecosystem: 'docker'
    directory: '/test/docker/*/Dockerfile*'
    schedule:
      interval: 'daily'
```

Will result in:

```
  - package-ecosystem: 'docker'
    directory: '/test/docker/container_1/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/test/docker/container_2/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/test/docker/weird_dockerfile/'
    schedule:
      interval: 'daily'
```
```

2024-03-01 12:47 UTC, atchertchian requested changes
See minor comments to address

2024-03-01 12:47 UTC, atchertchian commented on docs/README.md
> +    - [Generate Dependabot Glob Action](#generate-dependabot-glob-action)
Maybe it's not obvious but there are ordered alphabetically: do you mind moving it please?

2024-03-01 12:47 UTC, atchertchian commented on docs/README.md
> +```
```suggestion
```yml
```

(this is making pre-commit fail)

2024-03-01 12:47 UTC, atchertchian commented on docs/README.md
> +```
```suggestion
```yml
```

(this is making pre-commit fail)

2024-03-04 14:23 UTC, atchertchian approved these changes
LGTM!

2024-03-04 14:28 UTC, merged