OPSEXP-2149 Document recipe for quay.io image tag expire
Alfresco/alfresco-build-tools pull request #552
Opened 2024-03-27 14:59 UTC by gionn

### Checklist

- Jira Reference (also in PR title): OPSEXP-2149
- [README](https://github.com/Alfresco/alfresco-build-tools/blob/master/docs/README.md) updated after adding/changing behaviour of an action
- Proposed version increment for [release](https://github.com/Alfresco/alfresco-build-tools/blob/master/docs/README.md#release):
  - [ ] Patch (bugfix)
  - [x] Minor (new feature)
  - [ ] Major (breaking changes)
- External PR link where changes has been tested:

### Description

2024-03-28 09:56 UTC, dsibilio reviewed
Thanks for this! Left a few grammar checks, I would also suggest linking the official quay.io documentation that also talks about the time format to be used: https://access.redhat.com/documentation/it-it/red_hat_quay/3.2/html/use_red_hat_quay/working_with_tags#tag-expiration.

2024-03-28 09:56 UTC, dsibilio commented on docs/README.md
> +merge but we should avoid to pollute image registry with tags.
```suggestion
merge but we should avoid polluting the image registry with these tags.
```

2024-03-28 09:56 UTC, dsibilio commented on docs/README.md
> +With quay.io it can be easily achievable by setting on the docker image the label:
```suggestion
With quay.io, this can be easily achieved by setting the following label on the docker image:
```

2024-03-28 14:01 UTC, alxgomz requested changes
Do you mind adding a quick line dedicated to fabric8 which seems to still be used in acs-packaging at least:
e.g. `MAVEN_OPTIONS` set to `$MAVEN_OPTIONS -Ddocker.labels.${{ steps.vars.outputs.image_labels }}` (https://dmp.fabric8.io/#property-configuration) or similar?

2024-03-29 09:15 UTC, alxgomz submitted a review, later dismissed

2024-03-29 09:20 UTC, pmacius submitted a review, later dismissed

2024-03-29 09:20 UTC, dsibilio submitted a review, later dismissed

2024-03-29 09:20 UTC, dsibilio commented on docs/README.md
> +An example step which compute the label could be:
```suggestion
An example step which computes the label could be:
```

2024-03-29 09:20 UTC, dsibilio commented on docs/README.md
> +Then if you are using the `docker/build-push-action` action:
```suggestion
Then, if you are using the `docker/build-push-action` action:
```

2024-03-29 09:23 UTC, alxgomz submitted a review, later dismissed

2024-03-29 09:24 UTC, dsibilio approved these changes

2024-03-29 09:29 UTC, dsibilio approved these changes

2024-03-29 09:30 UTC, alxgomz approved these changes

2024-03-29 09:30 UTC, merged