OPSEXP-2743 Run ansible-galaxy via pipenv when available
Alfresco/alfresco-build-tools pull request #680
Opened 2024-07-10 12:57 UTC by pmacius

### Checklist

- Jira Reference (also in PR title): OPSEXP-2743
- [README](https://github.com/Alfresco/alfresco-build-tools/blob/master/docs/README.md) updated after adding/changing behaviour of an action
- Proposed version increment for [release](https://github.com/Alfresco/alfresco-build-tools/blob/master/docs/README.md#release):
  - [x] Patch (bugfix)
  - [ ] Minor (new feature)
  - [ ] Major (breaking changes)
- External PR link where changes has been tested: https://github.com/Alfresco/devops-engineering-iac/pull/87

### Description

2024-07-10 13:31 UTC, gionn requested changes

2024-07-10 13:31 UTC, gionn commented on .github/actions/install-galaxy-deps/action.yml
> +        if [ -f Pipfile ]; then
better check for `~/.cache/pipenv` existance

you can avoid duplicating the command either by:
* having a var which can be empty or contains `pipenv run`
* having a var for the entire ansible-galaxy command and args

2024-07-11 07:26 UTC, gionn reviewed
no versions.txt bump because you bump once the other PR is merged right?

2024-07-11 07:26 UTC, gionn commented on docs/README.md
> +Installs and cache ansible galaxy dependencies. When `~/.cache/pipenv` directory exists, installation is done on pipenv.
```suggestion
Installs and cache ansible galaxy dependencies. When `~/.cache/pipenv` directory exists, installation command is prefixed with `pipenv run`.
```

2024-07-11 08:16 UTC, gionn approved these changes

2024-07-11 08:21 UTC, alxgomz approved these changes

2024-07-11 08:23 UTC, merged